apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
spec:
  containers:
    - image: claudiuvintila/rabbitmq-kubernetes:v1
      name: rabbitmq
      env:
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: erlangCookie
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
spec:
  ports:
    - name: amqps
      protocol: TCP
      port: 5671
    - name: amqp
      protocol: TCP
      port: 5672
    - name: epmd
      protocol: TCP
      port: 4369
    - name: dist
      protocol: TCP
      port: 25672
    - name: admin
      protocol: TCP
      port: 15672
  selector:
    name: rabbitmq
  type: ClusterIP
